### PR TITLE
Use array_reduce in QueryModifications

### PR DESCRIPTION
**Pull request by szepeviktor**
Fast and simple.

### CODE REVIEW

**Comment by psorensen** [comment]
@szepeviktor Unfortunately this is causing a bug. See Screenshots below

## `main`
image

## `szepeviktor:patch-2`
image

**Review by psorensen — CHANGES_REQUESTED** [review]
This code causes a regression - see comment in PR.

**Comment by szepeviktor** [comment]
I am sorry.
The return statement was missing.
I do not write code daily.

**Comment by psorensen** [comment]
Still no dice - the order doesn't appear to be preserved when using `array_reduce`. 
image

I'd say any potential performance savings from this improvement is negligible. I'm going to close the issue and keep as is, but I do appreciate your contibutions!

**Comment by szepeviktor** [comment]
Starting with `$posts`
```php
array (
  0 =>
  array (
    'id' => 7,
    'name' => 'seven',
  ),
  1 =>
  array (
    'id' => 4,
    'name' => 'four',
  ),
  2 =>
  array (
    'id' => 5,
    'name' => 'five',
  ),
)
```
the original function returns
```php
array (
  0 => 7,
  1 => 4,
  2 => 5,
)
```
the new one returns
```php
array (
  0 => 7,
  1 => 4,
  2 => 5,
)
```

**Pull request closed without merging**
